#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["requests>=2.31"]
# ///
"""Generate the AIpps gallery from the trustable-ai catalog.

See spec/4-generate.md and spec/7-publish.md. Reads support/index.json — the
catalog regenerated in place by support/index.py, which build.sh runs first —
clones each *-templates repo for the per-application copy and icons, and writes
Zola sections under content/aipps/<group>/ plus the icons under static/aipps/.
The output is committed, so build.sh never needs the network.
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import requests

RAW = "https://raw.githubusercontent.com/{repo}/refs/heads/main/{path}"

HERE = Path(__file__).resolve().parent
CONTENT = HERE / "content" / "aipps"
STATIC = HERE / "static" / "aipps"
# The catalog is read from the support submodule rather than fetched, so the
# site is always generated from the index that is about to be published
# alongside it — see spec/7-publish.md.
INDEX = HERE / "support" / "index.json"
# The templates clones must stay outside content/: zola parses everything under
# it and a repo's bare README has no front matter, which fails the build.
WORK = HERE / ".templates"

# Written into every generated file; a directory whose _index.md carries it is
# ours to delete and rewrite, anything else under content/aipps/ is
# hand-written and left alone.
MARKER = "generated by generator.py — see spec/4-generate.md"

# A README that is only the workspace stub carries no information about the
# application, so such a page falls back to the catalog description instead.
STUB_READMES = {"# trustable workspace"}


def slug(text: str) -> str:
    """Group name to directory name: 'Utilities' -> 'utilities'."""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def toml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def templates_repo(app: dict) -> str | None:
    """The <owner>/<name>-templates repo an application's icon is served from.

    The catalog does not link an application to its templates repo directly;
    the icon URL is the only place that association is recorded.
    """
    match = re.match(
        r"https://raw\.githubusercontent\.com/([^/]+/[^/]+)/", app.get("icon", "")
    )
    return match.group(1) if match else None


def clone(repo: str, offline: bool) -> Path | None:
    """Clone or refresh a templates repo into its gitignored working copy."""
    WORK.mkdir(parents=True, exist_ok=True)
    dest = WORK / repo.split("/")[-1]
    if dest.exists():
        if not offline:
            subprocess.run(
                ["git", "-C", str(dest), "pull", "--quiet", "--ff-only"], check=False
            )
        return dest
    if offline:
        print(f"   ! {repo} not cloned and --offline given", file=sys.stderr)
        return None
    print(f"   cloning {repo}")
    result = subprocess.run(
        ["git", "clone", "--depth", "1", "--quiet", f"https://github.com/{repo}", str(dest)],
        check=False,
    )
    return dest if result.returncode == 0 else None


def fetch_readme(repo_url: str) -> str:
    """The application repo's README, used when the templates repo has no page."""
    repo = repo_url.removeprefix("https://github.com/").rstrip("/")
    try:
        response = requests.get(RAW.format(repo=repo, path="README.md"), timeout=20)
    except requests.RequestException:
        return ""
    return response.text if response.ok else ""


def body_for(app: dict, checkout: Path | None, checkouts: dict) -> str:
    """Page body: the templates repo's copy, else the application README.

    Like the icon, the copy for an application listed under two groups may sit
    in a sibling templates repo, so every checkout is tried before falling back
    to the application repo.
    """
    for source in [checkout] + list(checkouts.values()):
        if source is None:
            continue
        local = source / f"{app['name']}.md"
        if local.is_file():
            return local.read_text(encoding="utf-8")
    return fetch_readme(app["repo"])


def app_key(title: str) -> str:
    return re.sub(r"[^a-z0-9]", "", title.lower())


def strip_title(body: str, title: str, name: str) -> str:
    """Drop a leading `# Title` that only restates the frontmatter title.

    Most copy opens with a step heading ('# 1 - Application Foundation') that
    is real content, so only a heading naming the application goes. The match
    is loose in one direction: 'Database Manager' under the title 'AI Database
    Manager' is the same name, so a heading contained in the title (or equal to
    the catalog name) counts, while a longer heading is left alone.
    """
    lines = body.lstrip().splitlines()
    if lines and lines[0].startswith("#"):
        heading = app_key(lines[0].lstrip("#").strip())
        if heading and (heading in app_key(title) or heading == app_key(name)):
            return "\n".join(lines[1:]).lstrip()
    return body.strip()


def copy_icon(app: dict, checkout: Path | None, checkouts: dict) -> str | None:
    """Copy an application's icon out of the checkouts into static/aipps/.

    Two layouts are in use. A templates repo names the file after the
    application, <name>.png; an application's own repo publishes it as
    screenshot.png, which the catalog now points at. Either is published as
    /aipps/<name>.png so the page URL does not depend on where it came from.

    An application listed under two groups points at the icon of only one of
    them (truk8s is in Demo and Utilities but the PNG lives only in
    trutil-templates), so any checkout holding the file will do.
    """
    candidates = [checkout] + list(checkouts.values())
    for source in candidates:
        if source is None:
            continue
        for name in (f"{app['name']}.png", "screenshot.png"):
            icon = source / name
            # screenshot.png is per-repo, so only the application's own
            # checkout may answer with it — any other clone's screenshot
            # belongs to a different application.
            if name == "screenshot.png" and source is not checkout:
                continue
            if icon.is_file():
                STATIC.mkdir(parents=True, exist_ok=True)
                published = f"{app['name']}.png"
                shutil.copyfile(icon, STATIC / published)
                return f"/aipps/{published}"
    return None


def clean_generated() -> None:
    """Remove previously generated group directories, keeping everything else."""
    for child in sorted(CONTENT.iterdir()):
        index = child / "_index.md"
        if child.is_dir() and index.is_file() and MARKER in index.read_text(encoding="utf-8"):
            shutil.rmtree(child)


def clean_icons(applications: dict) -> int:
    """Delete icons of applications the catalog no longer lists.

    copy_icon only ever writes <name>.png, so anything else under static/aipps/
    belongs to an application that has since left the catalog and would
    otherwise stay published forever.
    """
    if not STATIC.is_dir():
        return 0
    keep = {f"{app['name']}.png" for apps in applications.values() for app in apps}
    removed = 0
    for icon in sorted(STATIC.glob("*.png")):
        if icon.name not in keep:
            icon.unlink()
            removed += 1
    return removed


def write_group(group: str, apps: list[dict], weight: int, checkouts: dict) -> int:
    directory = CONTENT / slug(group)
    directory.mkdir(parents=True, exist_ok=True)
    directory.joinpath("_index.md").write_text(
        "+++\n"
        f"title = {toml_str(group)}\n"
        f"description = {toml_str(f'{group} you can start from, ready to run on your own infrastructure.')}\n"
        f"weight = {weight}\n"
        'sort_by = "weight"\n'
        'template = "section.html"\n'
        'page_template = "page.html"\n'
        "[extra]\n"
        f"generated = {toml_str(MARKER)}\n"
        "+++\n",
        encoding="utf-8",
    )

    written = 0
    for order, app in enumerate(apps, start=1):
        checkout = checkouts.get(templates_repo(app))
        title = app.get("title") or app["name"]
        body = strip_title(body_for(app, checkout, checkouts), title, app["name"])
        if body.strip().lower() in STUB_READMES or not body.strip():
            body = app.get("description", "")
        icon = copy_icon(app, checkout, checkouts)

        front = [
            "+++",
            f"title = {toml_str(title)}",
            f"description = {toml_str(app.get('description', ''))}",
            f"weight = {order * 10}",
            "[extra]",
            f"generated = {toml_str(MARKER)}",
            f"group = {toml_str(group)}",
            f"repo = {toml_str(app['repo'])}",
        ]
        if icon:
            front.append(f"icon = {toml_str(icon)}")
        front += ["+++", ""]

        directory.joinpath(f"{app['name']}.md").write_text(
            "\n".join(front) + body.strip() + "\n", encoding="utf-8"
        )
        written += 1
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--offline",
        action="store_true",
        help="reuse the existing template clones instead of pulling them",
    )
    args = parser.parse_args()

    if not INDEX.is_file():
        print(
            f"error: {INDEX} not found — the support submodule is not checked "
            "out. Run: git submodule update --init support",
            file=sys.stderr,
        )
        return 1
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    print(f">> reading {INDEX.relative_to(HERE)}")

    applications = index.get("applications", {})

    # One clone per templates repo, shared by every application in it.
    repos = {
        repo
        for apps in applications.values()
        for app in apps
        if (repo := templates_repo(app))
    }
    checkouts = {repo: clone(repo, args.offline) for repo in sorted(repos)}

    clean_generated()

    total = 0
    for weight, (group, apps) in enumerate(applications.items(), start=1):
        count = write_group(group, apps, weight * 10, checkouts)
        print(f">> {group}: {count} pages")
        total += count

    stale = clean_icons(applications)
    if stale:
        print(f">> removed {stale} icons no longer in the catalog")

    print(f">> generated {total} pages in {len(applications)} groups")
    return 0


if __name__ == "__main__":
    sys.exit(main())
